In [1]:
import numpy as np

In [10]:
path = "/Users/petrumilev/Documents/projects_python/project_girona_donostia/data_ultrafine.csv"
A = np.loadtxt(path, skiprows=1, dtype=str, delimiter=",")
for i in A:
    print(i)

['lib_bnnt_M062X_Z-48.FChk' '0.0' '0.0' '-0.0004800000000000002'
 '-1286.938565833217' '1.809662726320252' '367.279941193813'
 '-2901.486469906116']
['lib_bnnt_M062X_Z-47.FChk' '0.0' '0.0' '-0.0004700000000000002'
 '-1286.938547754912' '1.805990071822592' '367.2509728324576'
 '-2892.426912034659']
['lib_bnnt_M062X_Z-46.FChk' '0.0' '0.0' '-0.0004600000000000002'
 '-1286.938529713534' '1.802317706569539' '367.2220873068306'
 '-2885.016594060996']
['lib_bnnt_M062X_Z-45.FChk' '0.0' '0.0' '-0.0004500000000000002'
 '-1286.938511708588' '1.798645629886848' '367.1932667965269'
 '-2879.422795144092']
['lib_bnnt_M062X_Z-44.FChk' '0.0' '0.0' '-0.0004400000000000002'
 '-1286.9384937405' '1.794973841023369' '367.1644921634656'
 '-2875.818952458195']
['lib_bnnt_M062X_Z-43.FChk' '0.0' '0.0' '-0.0004300000000000002'
 '-1286.938475809181' '1.791302339946299' '367.1357430530618'
 '-2874.409263384374']
['lib_bnnt_M062X_Z-42.FChk' '0.0' '0.0' '-0.0004200000000000002'
 '-1286.93845791447' '1.78763112622232

In [11]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
line = "scf(conver=11,maxcycles=300) integral(grid=sg1grid,acc2e=14)"
a = "grid=sg1grid"
a in line

True

In [13]:
a = "GFINPUT IOP(6/7=3) IOp(6/80=1) IOp(3/59=10) IOp(99/18=-1)"
a[:-1]

'GFINPUT IOP(6/7=3) IOp(6/80=1) IOp(3/59=10) IOp(99/18=-1'

In [4]:
path = "/Users/petrumilev/Documents/projects_python/project_girona_donostia/diff_data/data_alot.csv"
np.loadtxt(path,skiprows = 1, dtype = str)

array(['lib_bnnt_M062X_Z-48.FChk,0.0,0.0,-0.0004800000000000002,-1286.9392250207,1.809564415101229,367.2578975052928,-1969.82673136309,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan',
       'lib_bnnt_M062X_Z-47.FChk,0.0,0.0,-0.0004700000000000002,-1286.939206943463,1.805891931877716,367.2390234756044,-1804.411224316963,1.8058902000017694377,nan,nan,nan,nan,nan,nan,nan,nan,nan',
       'lib_bnnt_M062X_Z-46.FChk,0.0,0.0,-0.0004600000000000002,-1286.939188902896,1.802219629039548,367.221819695828,-1635.775239428722,1.8022224000047158601,1.802218474999950212,nan,nan,nan,nan,nan,nan,nan,nan',
       'lib_bnnt_M062X_Z-45.FChk,0.0,0.0,-0.0004500000000000002,-1286.939170899015,1.79854748978126,367.2063177173333,-1464.275145941051,1.7985467499981309863,1.7985477500009892843,1.7985473000007671155,nan,nan,nan,nan,nan,nan,nan',
       'lib_bnnt_M062X_Z-44.FChk,0.0,0.0,-0.0004400000000000002,-1286.939152931961,1.794875496962188,367.1925425980301,-1290.394349181479,1.7948730999972627085,1.7948758500002658