In [74]:
import numpy as np
import ast
import re

In [4]:
A = read("File_name")
for i in range(5):
    a = obj
    for i1 in range(10):
        A = print_derivative(A, n_point = 2*i + 1, step = i1)
        
        
    


array([1, 2, 3, 1, 2, 3])

In [15]:
do_my_job("path/to/file")

array([ 1,  2,  3,  4,  5, 10, 20, 30])

/var/folders/ym/26b79b9x6wg59yqrctz2c40h0000gn/T/ipykernel_76171/3497693437.py:8: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  result_array = np.array([tuple(my_array)] + [my_list], dtype=[('arr', 'int', 3), ('list', 'O', 1)])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [19]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a)
a.extend(b)
print(a)

[1, 2, 3]
[1, 2, 3, 4, 5, 6]


False

In [73]:
a = "azazaazaa {'x':1,'y':2,'z':3}"
A = a.split(" ")
A = ast.literal_eval("{'x': 1, 'y': 2, 'z': 3}")
print(A)

{'x': 1, 'y': 2, 'z': 3}


In [40]:
a = np.array([1,2, 2,12312412, 3,12312412, np.NaN])
np.round(np.NaN, 2)

nan

In [66]:
A = np.array([[1.123, 2.123, 3.123], [4.123, 5.123, 6.123], [7.123, 8.123, np.NaN]])

In [68]:
np.round(A[:,2], 2)

array([3.12, 6.12,  nan])

In [ ]:
import girona_donostia as gd

A = get_list_of_propreties_for_fchk_in_a_folder()

In [84]:
s = "kw_1, kw_2, kw_3(text, in, kw3)"
A = re.split(r'\s(?![^(]*\))',s)
A

['kw_1,', 'kw_2,', 'kw_3(text, in, kw3)']

In [81]:
str = "dwvewfv(word1), (word2), wvfwvw (word3)"
re.findall(r'\((.*?)\)', str)

['word1', 'word2', 'word3']

In [85]:
a = "dvdsv"
a.split("()")

['dvdsv']

In [91]:
def func(d, a, b, c, extension = False):
    if extension:
        print("test")
    return d + a + b + c
i = [1, 2, 3, True]

func(6, *i)

test


12

In [92]:
a = "***kw_e_field***"
"kw_e_field" in a



True

In [94]:
A = ['gen_e_field_direction', 1, 2, 3]
"gen_e_field_direction" in A

True

In [1]:
a = "#P M062X"
"#" in a

True

In [2]:
a.strip()

'#P M062X'

In [3]:
a = 10**(-16)

In [5]:
a

1e-16

In [7]:
a == 0

False

In [9]:
A = -0.0
print(abs(A))

0.0


In [1]:
a = "Example_how_we_want_X-1.41e-04_Y-1.41e-04.com"
"X+0" in a

False

In [2]:
path = "/Users/petrumilev/Documents/projects_python/File_for_proj_girona_donostia/Test_Input/Example_how_we_want.txt"

with open(path, "a") as file:
    file.write("ArithmeticError")

In [19]:
import os 
a = "word1"
b = "word2"
c = "word3"
os.path.join(a,b,c)

'word1/word2/word3'

In [23]:
a = "word1 word2 word3"
a.replace("word2", "")
a

'word1 word2 word3'

In [24]:
path = "/Users/petrumilev/Documents/projects_python/File_for_proj_girona_donostia/Test_Input"
os.listdir(path)

['Example_how_we_want_X-7.07e-05_Y-7.07e-05.com',
 '.DS_Store',
 'Example_how_we_want_X+7.07e-05_Y+7.07e-05.com',
 'Example_how_we_want_X+3.54e-04_Y+3.54e-04.com',
 'Example_how_we_want_X+2.12e-04_Y+2.12e-04.com',
 'Example_how_we_want_X-2.83e-04_Y-2.83e-04.com',
 'Example_how_we_want_X-3.54e-04_Y-3.54e-04.com',
 'Example_how_we_want_X-2.12e-04_Y-2.12e-04.com',
 'Example_how_we_want_X+2.83e-04_Y+2.83e-04.com',
 'Example_how_we_want_X+0_Y+0.com',
 'Example_how_we_want_X+1.41e-04_Y+1.41e-04.com',
 'Example_how_we_want_X-1.41e-04_Y-1.41e-04.com',
 'Example_how_we_want.txt']

In [1]:
a = "@/Users/petrumilev/Documents/projects_python/project_girona_donostia/jupyter_notebook/geometry_test.txt"
"@" in a

True

In [2]:
import numpy as np 

In [15]:
def split_text_for_inp(text):
    result = ""
    parens_open = 0
    for char in text:
        if char =='(':
            parens_open += 1
        elif char == ')':
            parens_open -= 1
        if char == ',' and parens_open == 0:
            char = ""
        if char == ' ' and parens_open == 0:
            print(char)
            char = ";"
        result += char
    return result.split(";")

def get_inp_text(text):
    result = ""
    parens_open = 0
    for char in text:
        if char == ')':
            parens_open -= 1
        if parens_open > 0:
            result += char
        if char =='(':
            parens_open += 1
    if result == "":
        return None
    else: return result
                


In [23]:
a = "gen_e_field_direction(1, 90, 45, -0.0005, 0.0005, 11, spherical, linear) new_kw update_old_chk(n-1) basis_set(origin) change_kw(sg1, sg2) change_kw(cphf(grids=sg1, delete)) read_geom() zip([sg1, sg2, sg3, sg4],[cphf(grid=sg1), delete],[IOp(9/75=2), IOp(9/75=1)])"
A = split_text_for_inp(a)
A

['gen_e_field_direction(1, 90, 45, -0.0005, 0.0005, 11, spherical, linear)',
 'new_kw',
 'update_old_chk(n-1)',
 'basis_set(origin)',
 'change_kw(sg1, sg2)',
 'change_kw(cphf(grids=sg1, delete))',
 'read_geom()',
 'zip([sg1, sg2, sg3, sg4],[cphf(grid=sg1), delete],[IOp(9/75=2), IOp(9/75=1)])']

In [31]:
line = "wdvgewrgf zip((sg1, sg2, sg3, sg4), (cphf(grid=sg1), delete), (IOp(9/75=2), IOp(9/75=1)))wd fwe fwe "
a = line.find("zip((sg1, sg2, sg3, sg4), (cphf(grid=sg1), delete), (IOp(9/75=2), IOp(9/75=1)))")
print(a)
new_string = line[:a] + line[a + len(line):]
print(new_string)

10
wdvgewrgf 


In [34]:
def parse(text):
  result = []
  parens_open = 0

  for char in text:
    if char == '(':
      parens_open += 1
      result.append(char)
    elif char == ')' and parens_open:
      if parens_open == 1 and result[-1] == '(':
        result.pop()  # Removes empty unnested parens i.e. '()'
      else:
        result.append(char)
      parens_open -= 1

    elif char == '\n' and result and result[-1] != '\n':
      # ensure only one carriage return between text
      result.append(char)
    elif parens_open:
      result.append(char)

  return ''.join(result)


In [44]:
a = "zip((sg1, sg2, sg3, sg4),(cphf(grid=sg1), delete),(IOp(9/75=2), IOp(9/75=1)))"
b = parse(a)
print(b)
c = parse(b)
c

((sg1, sg2, sg3, sg4),(cphf(grid=sg1), delete),(IOp(9/75=2), IOp(9/75=1)))


'((sg1, sg2, sg3, sg4),(cphf(grid=sg1), delete),(IOp(9/75=2), IOp(9/75=1)))'

In [37]:
line = "wdvgewrgf zip((sg1, sg2, sg3, sg4), (cphf(grid=sg1), delete), (IOp(9/75=2), IOp(9/75=1))) wd fwe fwe "
str_to_remove = "zip((sg1, sg2, sg3, sg4), (cphf(grid=sg1), delete), (IOp(9/75=2), IOp(9/75=1)))"
a = line.find(str_to_remove)
print(a)
new_string = line[:a] + line[a + len(str_to_remove):]
print(new_string)

10
wdvgewrgf  wd fwe fwe 


In [35]:
line[a + len(line):]

''